export type Lang = "en" | "es";

export const copy = {
  en: {
    academy: "G.A.Menon Academy",
    hub: "Claude Certification Learning Hub",
    tagline:
      "Foundation notes, exam-style practice, and session videos — in English and Spanish.",
    navNotes: "Notes",
    navQuiz: "Quizzes",
    navVideos: "Videos",
    lang: "English",
    startNotes: "Open the notes",
    startQuiz: "Practice quiz",
    startVideos: "Video links",
    modulesTitle: "Modules",
    modulesLead:
      "Twelve live sessions, chapter by chapter. English and Spanish are separate views — use the language toggle.",
    chapters: "Chapters",
    relatedVideos: "Videos for this module",
    addLink: "No link yet — add a URL in data/videos.json",
    quizTitle: "Exam-style quizzes",
    quizLead:
      "100 original practice items weighted like CCDV-F (applications, models, agents, prompting, tools/MCP, security, Claude Code, eval). Each attempt draws a fresh sample. Not official Anthropic or Pearson questions.",
    practice20: "Practice set (20 of 100)",
    exam25: "Exam-style set (25, domain-weighted)",
    byModule: "Quiz by module",
    start: "Start",
    next: "Next",
    back: "Back",
    submit: "Submit quiz",
    question: "Question",
    of: "of",
    selectN: "Select {n}",
    score: "Score",
    strong: "You did well on",
    weak: "Spend more time on",
    retry: "New random set",
    reviewNotes: "Open matching notes",
    home: "Home",
    videosTitle: "Session videos",
    videosLead:
      "Add your recording URLs in data/videos.json (LMS, Stream, Drive). Empty cards wait for a link — no login required.",
    openVideo: "Open video",
    missingUrl: "Link not added yet",
    footer:
      "G.A.Menon Academy · study aid only · not official Anthropic exam material. Prefer docs.claude.com when recordings age.",
    disclaimer:
      "Classroom numbers (question counts, pass marks) may differ from the current Pearson guide. Trust the live exam guide on Anthropic Partner Academy.",
    wellDone: "Keep that approach for those domains.",
    studyHint: "Re-read the linked module, then retry a quiz.",
    progress: "Progress",
    pickAnswer: "Choose an answer to continue.",
    domains: {
      applications: "Applications and integration",
      models: "Model selection and cost",
      agents: "Agents and workflows",
      prompt: "Prompt and context",
      tools: "Tools and MCP",
      security: "Security and safety",
      "claude-code": "Claude Code",
      eval: "Eval, testing, debugging",
    },
  },
  es: {
    academy: "G.A.Menon Academy",
    hub: "Centro de aprendizaje · Certificación Claude",
    tagline:
      "Apuntes Foundation, práctica tipo examen y vídeos de sesión — en inglés y en español.",
    navNotes: "Apuntes",
    navQuiz: "Cuestionarios",
    navVideos: "Vídeos",
    lang: "Español",
    startNotes: "Abrir los apuntes",
    startQuiz: "Cuestionario",
    startVideos: "Enlaces de vídeo",
    modulesTitle: "Módulos",
    modulesLead:
      "Doce sesiones en directo, capítulo a capítulo. Inglés y español van en vistas distintas: usad el conmutador de idioma.",
    chapters: "Capítulos",
    relatedVideos: "Vídeos de este módulo",
    addLink: "Aún no hay enlace — añadid una URL en data/videos.json",
    quizTitle: "Cuestionarios tipo examen",
    quizLead:
      "100 ítems originales ponderados como CCDV-F (aplicaciones, modelos, agentes, prompting, tools/MCP, seguridad, Claude Code, eval). Cada intento sortea una muestra nueva. No son preguntas oficiales de Anthropic ni de Pearson.",
    practice20: "Práctica (20 de 100)",
    exam25: "Simulacro (25, ponderado por dominio)",
    byModule: "Por módulo",
    start: "Empezar",
    next: "Siguiente",
    back: "Atrás",
    submit: "Enviar cuestionario",
    question: "Pregunta",
    of: "de",
    selectN: "Elegid {n}",
    score: "Puntuación",
    strong: "Lo habéis hecho bien en",
    weak: "Conviene reforzar",
    retry: "Otra muestra aleatoria",
    reviewNotes: "Abrir apuntes relacionados",
    home: "Inicio",
    videosTitle: "Vídeos de las sesiones",
    videosLead:
      "Añadid las URLs en data/videos.json (LMS, Stream, Drive). Las tarjetas vacías esperan un enlace. No hace falta iniciar sesión.",
    openVideo: "Abrir vídeo",
    missingUrl: "Enlace aún no añadido",
    footer:
      "G.A.Menon Academy · material de estudio · no es el examen oficial de Anthropic. Primad docs.claude.com si la grabación queda antigua.",
    disclaimer:
      "Las cifras de clase (número de preguntas, nota de corte) pueden diferir de la guía Pearson vigente. Consultad la guía de examen en Anthropic Partner Academy.",
    wellDone: "Mantened ese criterio en esos dominios.",
    studyHint: "Releed el módulo enlazado y repetid un cuestionario.",
    progress: "Progreso",
    pickAnswer: "Elegid una respuesta para seguir.",
    domains: {
      applications: "Aplicaciones e integración",
      models: "Selección de modelo y coste",
      agents: "Agentes y flujos",
      prompt: "Prompt y contexto",
      tools: "Herramientas y MCP",
      security: "Seguridad",
      "claude-code": "Claude Code",
      eval: "Eval, pruebas y depuración",
    },
  },
} as const;
