export type Lang = "en" | "es";

export const copy = {
  en: {
    academy: "G.A.Menon Academy",
    hub: "Claude Certification Learning Hub",
    tagline:
      "Notes and quizzes in English and Spanish. Session recordings are English only — one link per module.",
    navNotes: "Notes",
    navQuiz: "Quizzes",
    navVideos: "Videos",
    lang: "English",
    startNotes: "Open the notes",
    startQuiz: "Practice quiz",
    startVideos: "Video links",
    modulesTitle: "Modules",
    modulesLead:
      "Twelve live sessions, chapter by chapter. Notes are separate English and Spanish views — use the language toggle. Session recordings stay on the English video link.",
    chapters: "Chapters",
    relatedVideos: "English session recording",
    addLink: "No link yet — add the English recording URL in data/videos.json",
    videoLangBadge: "English recording · one link",
    quizTitle: "Exam-style quizzes",
    quizLead:
      "100 original practice items weighted like CCDV-F (applications, models, agents, prompting, tools/MCP, security, Claude Code, eval). Each attempt draws a fresh sample. Not official Anthropic or Pearson questions.",
    practice20: "Practice set (20 of 100)",
    exam25: "Exam-style set (25, domain-weighted)",
    byModule: "Quiz by module",
    start: "Start",
    next: "Next",
    back: "Back",
    submit: "Submit quiz",
    question: "Question",
    of: "of",
    selectOne: "Choose one answer.",
    selectN: "Select exactly {n} answers — {have} of {n} selected.",
    score: "Score",
    strong: "You did well on",
    weak: "Spend more time on",
    retry: "New random set",
    reviewNotes: "Open matching notes",
    home: "Home",
    videosTitle: "Session videos (English)",
    videosLead:
      "Masterclass recordings are English only. Notes and quizzes are the bilingual materials. Store one LMS, Stream, or Drive URL per session in academy/data/videos.json (url). Empty url leaves the card waiting. Do not commit MP4s.",
    videosHowToTitle: "Where to add videos",
    videosHowTo:
      "Edit academy/data/videos.json. Each module (m01–m12) has a single url. Paste the English session link. There is no second Spanish video field. After saving, redeploy (Vercel root directory: academy).",
    openVideo: "Open English recording",
    missingUrl: "English recording link not added yet",
    footer:
      "G.A.Menon Academy · study aid only · not official Anthropic exam material. Prefer docs.claude.com when recordings age.",
    disclaimer:
      "Classroom numbers (question counts, pass marks) may differ from the current Pearson guide. Trust the live exam guide on Anthropic Partner Academy.",
    wellDone: "Keep that approach for those domains.",
    studyHint: "Re-read the linked module, then retry a quiz.",
    progress: "Progress",
    pickAnswer: "Choose one answer to continue.",
    pickAnswers: "This item needs {n} answers ({have} selected) before Next unlocks.",
    domains: {
      applications: "Applications and integration",
      models: "Model selection and cost",
      agents: "Agents and workflows",
      prompt: "Prompt and context",
      tools: "Tools and MCP",
      security: "Security and safety",
      "claude-code": "Claude Code",
      eval: "Eval, testing, debugging",
    },
  },
  es: {
    academy: "G.A.Menon Academy",
    hub: "Centro de aprendizaje · Certificación Claude",
    tagline:
      "Apuntes y cuestionarios en inglés y en español. Las grabaciones de sesión están solo en inglés: un enlace por módulo.",
    navNotes: "Apuntes",
    navQuiz: "Cuestionarios",
    navVideos: "Vídeos",
    lang: "Español",
    startNotes: "Abrir los apuntes",
    startQuiz: "Cuestionario",
    startVideos: "Enlaces de vídeo",
    modulesTitle: "Módulos",
    modulesLead:
      "Doce sesiones en directo, capítulo a capítulo. Los apuntes van en vistas distintas de inglés y español: usad el conmutador. Las grabaciones siguen el enlace en inglés.",
    chapters: "Capítulos",
    relatedVideos: "Grabación de la sesión (inglés)",
    addLink: "Aún no hay enlace — añadid la URL de la grabación en inglés en data/videos.json",
    videoLangBadge: "Grabación en inglés · un enlace",
    quizTitle: "Cuestionarios tipo examen",
    quizLead:
      "100 ítems originales ponderados como CCDV-F (aplicaciones, modelos, agentes, prompting, tools/MCP, seguridad, Claude Code, eval). Cada intento sortea una muestra nueva. No son preguntas oficiales de Anthropic ni de Pearson.",
    practice20: "Práctica (20 de 100)",
    exam25: "Simulacro (25, ponderado por dominio)",
    byModule: "Por módulo",
    start: "Empezar",
    next: "Siguiente",
    back: "Atrás",
    submit: "Enviar cuestionario",
    question: "Pregunta",
    of: "de",
    selectOne: "Elegid una sola respuesta.",
    selectN: "Elegid exactamente {n} respuestas — {have} de {n} marcadas.",
    score: "Puntuación",
    strong: "Lo habéis hecho bien en",
    weak: "Conviene reforzar",
    retry: "Otra muestra aleatoria",
    reviewNotes: "Abrir apuntes relacionados",
    home: "Inicio",
    videosTitle: "Vídeos de las sesiones (inglés)",
    videosLead:
      "Las grabaciones del masterclass están solo en inglés. Lo bilingüe son los apuntes y los cuestionarios. Un enlace LMS, Stream o Drive por sesión en academy/data/videos.json (url). Si url está vacío, la tarjeta espera. No subáis MP4.",
    videosHowToTitle: "Dónde añadir los vídeos",
    videosHowTo:
      "Editad academy/data/videos.json. Cada módulo (m01–m12) tiene un solo url. Pegad el enlace de la sesión en inglés. No hay un segundo campo para un vídeo en español. Tras guardar, redesplegad (directorio raíz en Vercel: academy).",
    openVideo: "Abrir grabación en inglés",
    missingUrl: "Aún no hay enlace de la grabación en inglés",
    footer:
      "G.A.Menon Academy · material de estudio · no es el examen oficial de Anthropic. Primad docs.claude.com si la grabación queda antigua.",
    disclaimer:
      "Las cifras de clase (número de preguntas, nota de corte) pueden diferir de la guía Pearson vigente. Consultad la guía de examen en Anthropic Partner Academy.",
    wellDone: "Mantened ese criterio en esos dominios.",
    studyHint: "Releed el módulo enlazado y repetid un cuestionario.",
    progress: "Progreso",
    pickAnswer: "Elegid una respuesta para seguir.",
    pickAnswers: "Este ítem pide {n} respuestas ({have} marcadas) antes de desbloquear Siguiente.",
    domains: {
      applications: "Aplicaciones e integración",
      models: "Selección de modelo y coste",
      agents: "Agentes y flujos",
      prompt: "Prompt y contexto",
      tools: "Herramientas y MCP",
      security: "Seguridad",
      "claude-code": "Claude Code",
      eval: "Eval, pruebas y depuración",
    },
  },
} as const;
